In [9]:
#Json file
import pandas as pd
from io import StringIO
import json as json
json_file= '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
y = json.loads(json_file)
print(y)
df=pd.read_json(StringIO(json_file))
df

{'employee_name': 'James', 'email': 'james@gmail.com', 'job_profile': [{'title1': 'Team Lead', 'title2': 'Sr. Developer'}]}

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [11]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [23]:
#HTML File

url="https://countrycode.org/"
df=pd.read_html(url,match='ISO CODES',header=0)
df

[               COUNTRY COUNTRY CODE ISO CODES  POPULATION  AREA KM2  \
 0          Afghanistan           93  AF / AFG    29121286    647500
 1              Albania          355  AL / ALB     2986952     28748
 2              Algeria          213  DZ / DZA    34586184   2381740
 3       American Samoa        1-684  AS / ASM       57881       199
 4              Andorra          376  AD / AND       84000       468
 ..                 ...          ...       ...         ...       ...
 235  Wallis and Futuna          681  WF / WLF       16025       274
 236     Western Sahara          212  EH / ESH      273008    266000
 237              Yemen          967  YE / YEM    23495361    527970
 238             Zambia          260  ZM / ZMB    13460305    752614
 239           Zimbabwe          263  ZW / ZWE    11651858    390580

           GDP $USD
 0    20.65 Billion
 1     12.8 Billion
 2    215.7 Billion
 3    462.2 Million
 4      4.8 Billion
 ..             ...
 235            NaN
 236            NaN
 237  43.89 Billion
 238  22.24 Billion
 239  10.48 Billion

 [240 rows x 6 columns],
                COUNTRY COUNTRY CODE ISO CODES
 0          Afghanistan           93  AF / AFG
 1              Albania          355  AL / ALB
 2              Algeria          213  DZ / DZA
 3       American Samoa        1-684  AS / ASM
 4              Andorra          376  AD / AND
 ..                 ...          ...       ...
 235  Wallis and Futuna          681  WF / WLF
 236     Western Sahara          212  EH / ESH
 237              Yemen          967  YE / YEM
 238             Zambia          260  ZM / ZMB
 239           Zimbabwe          263  ZW / ZWE

 [240 rows x 3 columns]]

In [32]:
!pip install  xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
df=pd.read_csv("student-dataset.csv")
df.head()
df.to_csv("student-dataset.csv")
df

,Unnamed: 0,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,NaN,20,3.6,3.7,3.1,5.0,4,5.0,5
303,303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,NaN,20,3.6,3.9,4.0,5.0,5,5.0,3
304,304,304,Zachary Mulvahill,United States of America,Los Angeles,34.05,-118.24,M,NaN,20,3.2,3.4,3.9,5.0,5,5.0,3
305,305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,NaN,23,3.0,2.8,2.9,5.0,4,4.0,5
306,306,306,Dane Whittemore,Canada,Toronto,43.67,-79.42,M,NaN,21,3.8,3.2,4.0,5.0,5,4.0,5

In [35]:
#excel file
df=pd.read_excel("airline.xls")
df.to_pickle("airline.pickle")
pd.read_pickle("airline.pickle")

    YEAR       Y      W       R      L      K
0   1948   1.214  0.243  0.1454  1.415  0.612
1   1949   1.354  0.260  0.2181  1.384  0.559
2   1950   1.569  0.278  0.3157  1.388  0.573
3   1951   1.948  0.297  0.3940  1.550  0.564
4   1952   2.265  0.310  0.3559  1.802  0.574
5   1953   2.731  0.322  0.3593  1.926  0.711
6   1954   3.025  0.335  0.4025  1.964  0.776
7   1955   3.562  0.350  0.3961  2.116  0.827
8   1956   3.979  0.361  0.3822  2.435  0.800
9   1957   4.420  0.379  0.3045  2.707  0.921
10  1958   4.563  0.391  0.3284  2.706  1.067
11  1959   5.385  0.426  0.3856  2.846  1.083
12  1960   5.554  0.441  0.3193  3.089  1.481
13  1961   5.465  0.460  0.3079  3.122  1.736
14  1962   5.825  0.485  0.3783  3.184  1.926
15  1963   6.876  0.506  0.4180  3.263  2.041
16  1964   7.823  0.538  0.5163  3.412  1.997
17  1965   9.120  0.564  0.5879  3.623  2.257
18  1966  10.512  0.586  0.5369  4.074  2.742
19  1967  13.020  0.622  0.4443  4.710  3.564
20  1968  15.261  0.666  0.3052  5.217  4.767
21  1969  16.313  0.731  0.2332  5.569  6.511
22  1970  16.002  0.831  0.1883  5.495  7.627
23  1971  15.876  0.906  0.2023  5.334  8.673
24  1972  16.662  1.000  0.2506  5.345  8.331
25  1973  17.014  1.056  0.2668  5.662  8.557
26  1974  19.305  1.131  0.2664  5.729  9.508
27  1975  18.721  1.247  0.2301  5.722  9.062
28  1976  19.250  1.375  0.3452  5.762  8.262
29  1977  20.647  1.544  0.4508  5.877  7.474
30  1978  22.726  1.703  0.5877  6.108  7.104
31  1979  23.619  1.779  0.5346  6.852  6.874